"""Add local supply, immutable costs and operational procurement."""
from alembic import op
import sqlalchemy as sa
revision = "k04e6198cd21"
down_revision = "j93d5087bc10"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_type', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('contact', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("supplier_type IN ('partner_x','external_wholesaler')", name='ck_supplier_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_supply',
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('base_cost_minor', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(source_type = 'partner_x' AND supplier_id IS NOT NULL AND base_cost_minor IS NOT NULL AND base_cost_minor >= 0) OR (source_type != 'partner_x' AND supplier_id IS NULL AND base_cost_minor IS NULL)", name='ck_product_supply_partner'),
    sa.CheckConstraint("source_type IN ('own','partner_x','external')", name='ck_product_supply_source'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('supplier_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('supplier_sku', sa.String(length=255), nullable=True),
    sa.Column('purchase_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('availability', sa.String(length=20), server_default='on_request', nullable=False),
    sa.Column('availability_qty', sa.Integer(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('valid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('current_fx_rate_to_rub', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('fx_source', sa.String(length=20), nullable=True),
    sa.Column('fx_rate_date', sa.Date(), nullable=True),
    sa.Column('estimated_purchase_cost_rub_minor', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("availability IN ('on_request','confirmed','unavailable')", name='ck_offer_availability'),
    sa.CheckConstraint('current_fx_rate_to_rub IS NULL OR current_fx_rate_to_rub > 0', name='ck_offer_fx'),
    sa.CheckConstraint('purchase_price_minor >= 0 AND (availability_qty IS NULL OR availability_qty >= 0)', name='ck_offer_money_qty'),
    sa.ForeignKeyConstraint(['product_id'], ['product_supply.product_id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_offers_product_id'), 'supplier_offers', ['product_id'], unique=False)
    op.create_table('order_item_supply',
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('supplier_name', sa.String(length=255), nullable=True),
    sa.Column('cost_snapshot', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('own','partner_x','external')", name='ck_item_supply_source'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('order_item_id')
    )
    op.create_index(op.f('ix_order_item_supply_order_id'), 'order_item_supply', ['order_id'], unique=False)
    op.create_table('procurement_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='needed', nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('manual_fx_rate', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('manual_fx_by_manager_id', sa.Integer(), nullable=True),
    sa.Column('manual_fx_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('needed','requested','confirmed','received','cancelled','unavailable')", name='ck_procurement_status'),
    sa.ForeignKeyConstraint(['manual_fx_by_manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['supplier_offers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id')
    )
    op.create_index(op.f('ix_procurement_requests_order_id'), 'procurement_requests', ['order_id'], unique=False)
    op.create_table('x_settlements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('order_item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('base_cost_minor', sa.BigInteger(), nullable=False),
    sa.Column('sale_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('total_margin_minor', sa.BigInteger(), nullable=False),
    sa.Column('partner_margin_minor', sa.BigInteger(), nullable=True),
    sa.Column('our_margin_minor', sa.BigInteger(), nullable=True),
    sa.Column('partner_due_minor', sa.BigInteger(), nullable=True),
    sa.Column('calculation_version', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id')
    )
    op.create_index(op.f('ix_x_settlements_order_id'), 'x_settlements', ['order_id'], unique=False)
    op.create_table('supply_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procurement_id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['managers.id'], ),
    sa.ForeignKeyConstraint(['procurement_id'], ['procurement_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supply_events_procurement_id'), 'supply_events', ['procurement_id'], unique=False)
    # ### end Alembic commands ###
    op.execute("""CREATE FUNCTION protect_supply_snapshot() RETURNS trigger LANGUAGE plpgsql AS $$
    BEGIN
      IF TG_TABLE_NAME = 'x_settlements' THEN
        RAISE EXCEPTION 'immutable X settlement';
      END IF;
      IF OLD.source_type IS DISTINCT FROM NEW.source_type OR
         (OLD.cost_snapshot IS NOT NULL AND (OLD.cost_snapshot::jsonb IS DISTINCT FROM NEW.cost_snapshot::jsonb
          OR OLD.supplier_id IS DISTINCT FROM NEW.supplier_id OR OLD.supplier_name IS DISTINCT FROM NEW.supplier_name)) THEN
        RAISE EXCEPTION 'immutable supply snapshot';
      END IF;
      RETURN NEW;
    END $$""")
    op.execute("CREATE TRIGGER immutable_x BEFORE UPDATE ON x_settlements FOR EACH ROW EXECUTE FUNCTION protect_supply_snapshot()")
    op.execute("CREATE TRIGGER immutable_item_supply BEFORE UPDATE ON order_item_supply FOR EACH ROW EXECUTE FUNCTION protect_supply_snapshot()")

def downgrade():
    op.execute("DROP TRIGGER immutable_x ON x_settlements")
    op.execute("DROP TRIGGER immutable_item_supply ON order_item_supply")
    op.execute("DROP FUNCTION protect_supply_snapshot()")
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supply_events_procurement_id'), table_name='supply_events')
    op.drop_table('supply_events')
    op.drop_index(op.f('ix_x_settlements_order_id'), table_name='x_settlements')
    op.drop_table('x_settlements')
    op.drop_index(op.f('ix_procurement_requests_order_id'), table_name='procurement_requests')
    op.drop_table('procurement_requests')
    op.drop_index(op.f('ix_order_item_supply_order_id'), table_name='order_item_supply')
    op.drop_table('order_item_supply')
    op.drop_index(op.f('ix_supplier_offers_product_id'), table_name='supplier_offers')
    op.drop_table('supplier_offers')
    op.drop_table('product_supply')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
