"""Buying shared workspace; additive, no customer order references."""
from alembic import op
import sqlalchemy as sa
revision = "l15f7209de32"
down_revision = "k04e6198cd21"
branch_labels = None
depends_on = None

def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buying_checkouts',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('purchase_ids', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('buying_sessions',
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('digest')
    )
    op.create_table('buying_imports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('counts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buying_imports_supplier_id'), 'buying_imports', ['supplier_id'], unique=False)
    op.create_table('buying_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('send_state', sa.String(length=20), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('thread_id', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft','sent','received','cancelled','error')", name='ck_buying_purchase_status'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.create_index(op.f('ix_buying_purchases_supplier_id'), 'buying_purchases', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_buying_purchases_thread_id'), 'buying_purchases', ['thread_id'], unique=False)
    op.create_table('buying_suppliers',
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('parser', sa.JSON(), nullable=False),
    sa.CheckConstraint("currency IN ('RUB','USD')", name='ck_buying_currency'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('supplier_id')
    )
    op.create_table('buying_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['buying_purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buying_events_purchase_id'), 'buying_events', ['purchase_id'], unique=False)
    op.create_table('buying_products',
    sa.Column('product_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('normalized_name', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product_supply.product_id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_index(op.f('ix_buying_products_normalized_name'), 'buying_products', ['normalized_name'], unique=False)
    op.create_table('buying_replies',
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('thread_id', sa.String(length=255), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.String(length=20000), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_id'], ['buying_purchases.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_buying_replies_purchase_id'), 'buying_replies', ['purchase_id'], unique=False)
    op.create_table('buying_cart',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0 AND quantity <= 100000', name='ck_buying_cart_qty'),
    sa.ForeignKeyConstraint(['offer_id'], ['supplier_offers.id'], ),
    sa.PrimaryKeyConstraint('offer_id')
    )
    op.create_table('buying_offers',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('mapping_key', sa.String(length=500), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['supplier_offers.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('offer_id'),
    sa.UniqueConstraint('supplier_id', 'mapping_key', name='uq_buying_mapping')
    )
    op.create_table('buying_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('old_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('new_price_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['buying_imports.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['supplier_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_buying_price_history_offer_id'), 'buying_price_history', ['offer_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    raise RuntimeError("Buying history is durable: restore a verified backup")
