"""Fresh migrations in an isolated, uniquely named STAGING schema only."""
import json
import os
from pathlib import Path
from uuid import uuid4
from dotenv import load_dotenv
from sqlalchemy import create_engine, text
from alembic import command
from alembic.config import Config
from app.bot.staging_runner import validate_staging_config, activate_staging_config


def main():
    load_dotenv()
    staging = validate_staging_config(dict(os.environ))
    activate_staging_config(staging)
    schema = "oms_audit_" + uuid4().hex
    engine = create_engine(staging.database_url, connect_args={"connect_timeout": 10})
    report = {"schema": schema, "environment": "staging"}
    try:
        with engine.connect() as connection:
            connection.execute(text(f'CREATE SCHEMA "{schema}"'))
            connection.execute(text(f'SET search_path TO "{schema}"'))
            connection.commit()
            connection.dialect.default_schema_name = schema
            config = Config("alembic.ini")
            config.attributes["connection"] = connection
            command.upgrade(config, "head")
            connection.commit()
            report["fresh_upgrade"] = "passed"
            command.check(config)
            report["alembic_check"] = "passed"
    except Exception as error:
        report["error_type"] = type(error).__name__
        # Autogenerate differences contain schema names/types, never credentials.
        if type(error).__name__ == "AutogenerateDiffsDetected":
            report["schema_differences"] = str(error)
    finally:
        engine.dispose()
        directory = Path(".staging-artifacts")
        directory.mkdir(exist_ok=True)
        (directory / "validation.json").write_text(json.dumps(report, indent=2), encoding="utf-8")
        print(json.dumps(report))
    if report.get("alembic_check") != "passed":
        raise SystemExit(1)


if __name__ == "__main__":
    main()
